from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

# --- SUB-MODELS ---

class EC2Instance(BaseModel):
    instance_id: str = Field(
        ..., 
        description="Unique identifier for the EC2 instance"
    )
    instance_type: str = Field(
        ..., 
        description="Type of the instance, e.g., t3.micro"
    )
    state: Literal["pending", "running", "shutting-down", "terminated", "stopping", "stopped"] = Field(
        ..., 
        description="Current state of the EC2 instance"
    )
    cpu_utilization_percent: float = Field(
        ..., 
        description="Average CPU utilization percentage over the last period", 
        ge=0.0, 
        le=100.0
    )
    monthly_cost: float = Field(
        ..., 
        description="Estimated monthly cost of the instance in USD", 
        ge=0.0
    )
    tags: Dict[str, str] = Field(
        default_factory=dict, 
        description="Set of tags attached to the instance"
    )

class ElasticIP(BaseModel):
    allocation_id: str = Field(
        ..., 
        description="Allocation ID of the Elastic IP address"
    )
    public_ip: str = Field(
        ..., 
        description="The public IP address"
    )
    associated_instance_id: Optional[str] = Field(
        None, 
        description="ID of the EC2 instance this IP is associated with, if any"
    )
    monthly_cost: float = Field(
        ..., 
        description="Monthly cost of the Elastic IP in USD", 
        ge=0.0
    )

class IAMUser(BaseModel):
    user_name: str = Field(
        ..., 
        description="Name of the IAM user"
    )
    has_mfa_enabled: bool = Field(
        ..., 
        description="Whether the user has Multi-Factor Authentication enabled"
    )
    active_access_keys_count: int = Field(
        ..., 
        description="Number of active access keys associated with the user", 
        ge=0
    )
    days_since_key_rotation: int = Field(
        ..., 
        description="Number of days since the oldest active access key was rotated or created", 
        ge=0
    )

class S3Bucket(BaseModel):
    bucket_name: str = Field(
        ..., 
        description="The globally unique name of the S3 bucket"
    )
    is_public: bool = Field(
        ..., 
        description="Whether the bucket has public access via ACL or bucket policy"
    )
    size_gb: float = Field(
        ..., 
        description="Total size of the S3 bucket in Gigabytes", 
        ge=0.0
    )
    monthly_cost: float = Field(
        ..., 
        description="Estimated monthly cost of the bucket in USD", 
        ge=0.0
    )

class SecurityAlert(BaseModel):
    alert_id: str = Field(
        ..., 
        description="Unique identifier for the security alert"
    )
    severity: Literal["low", "medium", "high", "critical"] = Field(
        ..., 
        description="Severity level of the security alert"
    )
    description: str = Field(
        ..., 
        description="Description or summary of the security finding"
    )
    affected_resource_id: str = Field(
        ..., 
        description="ID of the resource (e.g., instance, bucket) affected by this security alert"
    )

class BillingSummary(BaseModel):
    total_monthly_spend: float = Field(
        ..., 
        description="Total accumulated spend in the current billing cycle in USD", 
        ge=0.0
    )
    projected_monthly_spend: float = Field(
        ..., 
        description="Projected total spend for the current billing cycle in USD", 
        ge=0.0
    )
    budget_limit: float = Field(
        ..., 
        description="The configured monthly budget limit in USD", 
        ge=0.0
    )

# --- OBSERVATION MODEL ---

class Observation(BaseModel):
    instances: List[EC2Instance] = Field(
        default_factory=list, 
        description="List of EC2 instances in the environment"
    )
    elastic_ips: List[ElasticIP] = Field(
        default_factory=list, 
        description="List of Elastic IPs in the environment"
    )
    iam_users: List[IAMUser] = Field(
        default_factory=list, 
        description="List of IAM users in the environment"
    )
    s3_buckets: List[S3Bucket] = Field(
        default_factory=list, 
        description="List of S3 buckets in the environment"
    )
    security_alerts: List[SecurityAlert] = Field(
        default_factory=list, 
        description="Active security alerts generated by security monitoring"
    )
    billing_summary: BillingSummary = Field(
        ..., 
        description="Current billing and cost summary"
    )

# --- ACTION MODELS ---

class TerminateInstanceAction(BaseModel):
    action_type: Literal["terminate_instance"] = Field("terminate_instance", description="Action type discriminator")
    instance_id: str = Field(..., description="ID of the EC2 instance to terminate")

class DownsizeInstanceAction(BaseModel):
    action_type: Literal["downsize_instance"] = Field("downsize_instance", description="Action type discriminator")
    instance_id: str = Field(..., description="ID of the EC2 instance to downsize")
    new_instance_type: str = Field(..., description="The target instance type to downsize to (e.g., t3.nano)")

class ReleaseElasticIPAction(BaseModel):
    action_type: Literal["release_elastic_ip"] = Field("release_elastic_ip", description="Action type discriminator")
    allocation_id: str = Field(..., description="Allocation ID of the Elastic IP to release")

class RevokeIAMKeyAction(BaseModel):
    action_type: Literal["revoke_iam_key"] = Field("revoke_iam_key", description="Action type discriminator")
    user_name: str = Field(..., description="Name of the IAM user")
    access_key_id: str = Field(..., description="Access Key ID to revoke/deactivate")

class ApplyTagAction(BaseModel):
    action_type: Literal["apply_tag"] = Field("apply_tag", description="Action type discriminator")
    resource_id: str = Field(..., description="ID of the resource to apply the tag to")
    tag_key: str = Field(..., description="The key of the tag")
    tag_value: str = Field(..., description="The value of the tag")

class BlockIPAction(BaseModel):
    action_type: Literal["block_ip"] = Field("block_ip", description="Action type discriminator")
    ip_address: str = Field(..., description="The IPv4 address to block (e.g., via WAF or NACL)")

class NoOpAction(BaseModel):
    action_type: Literal["no_op"] = Field("no_op", description="Take no action during this step")

Action = Union[
    TerminateInstanceAction,
    DownsizeInstanceAction,
    ReleaseElasticIPAction,
    RevokeIAMKeyAction,
    ApplyTagAction,
    BlockIPAction,
    NoOpAction
]

# --- STEP RESULT MODEL ---

class StepResult(BaseModel):
    observation: Observation = Field(
        ..., 
        description="The state of the environment after applying the action"
    )
    reward: float = Field(
        ..., 
        description="The scalar reward received for the previous action"
    )
    done: bool = Field(
        ..., 
        description="Indicates if the episode has ended (e.g., goals achieved or budget exceeded)"
    )
    info: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Additional diagnostic information and metrics from the environment"
    )
